language: r
cache: packages

r: bioc-release

bioc_packages:
   - MSnbase
   - Pbase
   - RforProteomics
   - Biobase
   - mzR
   - mzID
   - rpx
   - MLInterfaces
   - pRoloc
   - pRolocdata
   - BiocInstaller
   - rTANDEM
   - BiocStyle
   - AnnotationHub
   - MSGFplus
   - Biostrings
   - UniProt.ws
   - biomaRt
   - msmsTests

r_packages:
   - lattice
   - utils
   - gridExtra
   - gplots
   - rmarkdown
   - knitr
    
notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk
