language: r
cache: packages

sudo: true
apt_packages: libnetcdf-dev

r: bioc-release

r_check_args: --no-vignettes

notifications:
  email:
    on_success: lg390@cam.ac.uk
    on_failure: lg390@cam.ac.uk
